#!/usr/bin/env bash
#
# kfetch - tiny system info for linux.

export LC_ALL=C

# ===== INFO =====

# host
host="$(< /etc/hostname)"

# distro
. /etc/os-release
os="${NAME:-Linux}"
[[ -f "/bedrock/etc/os-release" ]] && os="bedrock"

# kernel
read -r s s kernel s < /proc/version

# shell
shell="${SHELL##*/}"

# model
model="$(< /sys/devices/virtual/dmi/id/product_version) "
model+="$(< /sys/devices/virtual/dmi/id/product_name)"
model="${model//*O.E.M*}"

# memory
while IFS=: read -r a b; do
    b=${b/kB}

    case $a in
        MemTotal)((mem_used+=b,mem_total=b)) ;;
        Shmem)((mem_used+=b)) ;;
        MemFree|Buffers|Cached|SReclaimable) ((mem_used-=b)) ;;
    esac
done </proc/meminfo

((mem_used/=1024,mem_total/=1024))
memory="${mem_used}MiB / ${mem_total}MiB"

# uptime
s="$(< /proc/uptime)"
s="${s/.*}"
((d=s/60/60/24, h=s/60/60%24, m=s/60%60))
((d)) && uptime+="${d}d "
((h)) && uptime+="${h}h "
((m)) && uptime+="${m}m"

# ===== DEFINE COLORS ======
bold="[1m"
black="[30m"
red="[31m"
green="[32m"
yellow="[33m"
blue="[34m"
magenta="[35m"
cyan="[36m"
white="[37m"
reset="(B[m"

# you can change these, if you want
lc="$reset$bold$blue"         # labels
nc="$reset$bold$blue"         # user and hostname
ic="$reset$bold$white"        # info
c0="$reset$bold$blue"         # first color

# ===== OUTPUT =====

# For Arch users:
#
#        /\      
#       /  \     
#      /\   \    
#     /  __  \   
#    /  (  )  \  
#   / __|  |__\\ 
#  /.`        `.\

# For Alpine users:
#
#        /\ 
#       /  \ 
#      / /\ \  /\ 
#     / /  \ \/  \
#    / /    \ \/\ \   
#   / / /|   \ \ \ \ 
#  /_/ /_|    \_\ \_\ 

echo "

$c0      .--.      $nc$USER$ic@$nc$host$reset
$c0     |o_o |     ${lc}OS: $ic$os$reset
$c0     |:_/ |     ${lc}SH: $ic$shell$reset
$c0    //   \\ \\    ${lc}MO: $ic$model$reset
$c0   (|     | )   ${lc}UP: $ic$uptime$reset 
$c0  /'\\_   _/\`\   ${lc}ME: $ic$memory$reset
$c0  \\___)=(___/   ${lc}KE: $ic${kernel}$reset

"

# EOF
